meta:
  engine: 4.1.0
units:
  $default_width: 18
  $default_height: 17
  kx: cx
  ky: cy
  p: 2
  px: kx + p
  py: ky + p
  WT: 2
points:
  zones:
    matrix:
      key:
        padding: cy
        spread: cx
      anchor:
        rotate: 5
      columns:
        outer:
        pinky:
        ring:
          key.origin: [-12, -19]
          key.stagger: 12
        middle:
          key.stagger: 5
        index:
          key.stagger: -6
        inner:
          key.stagger: 0
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        near:
        home:
          key.spread: 21.25
          key.splay: -20
          key.origin: [-11.75, -9]
        far:
          key.spread: 21.25
          key.splay: -20
          key.origin: [-9.5, -9]
      rows:
        thumb:
  rotate: -20
  mirror:
    ref: matrix_pinky_home
    distance: 223.7529778
outlines:
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_outer_bottom
          shift: [-.5px, -.5py]
        - ref: matrix_pinky_bottom
          shift: [.5px,-.5py]
        - ref: matrix_ring_bottom
          shift: [p-.5px,-.5py]
        - ref: matrix_ring_bottom
          shift: [.5px,-.5py]
        - ref: matrix_middle_bottom
          shift: [p-.5px,-.5py]
        - ref: matrix_middle_bottom
          shift: [.5px-p,-.5py]
        - ref: matrix_index_bottom
          shift: [-.5px,-.5py]
        - ref: matrix_index_bottom
          shift: [1,-.5py]
        - ref: thumbfan_near_thumb
          shift: [-.5px,-.5py]
        - ref: thumbfan_near_thumb
          shift: [.5px,-.5py]
        - ref: thumbfan_home_thumb
          shift: [-.5px,-.5py]
        - ref: thumbfan_home_thumb
          shift: [.5px,-.5py]
        - ref: thumbfan_far_thumb
          shift: [-.5px,-.5py]
        - ref: thumbfan_far_thumb
          shift: [.5px,-.5py]
        - ref: thumbfan_far_thumb
          shift: [.5px,.5py]
        - ref: matrix_inner_bottom
          shift: [1.75px,-.5py]
        - ref: matrix_inner_top
          shift: [1.75px,.5py]
        - ref: matrix_index_top
          shift: [-.5px+p,.5py]
        - ref: matrix_middle_top
          shift: [.5px,.5py]
        - ref: matrix_middle_top
          shift: [-.5px,.5py]
        - ref: matrix_ring_top
          shift: [.5px-p,.5py]
        - ref: matrix_ring_top
          shift: [-.5px,.5py]
        - ref: matrix_pinky_top
          shift: [.5px-p,.5py]
  base:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5px-WT, 0.5py+WT]
        - ref: matrix_outer_bottom
          shift: [-.5px-WT, -.5py-WT]
        - ref: matrix_pinky_bottom
          shift: [.5px+WT,-.5py-WT]
        - ref: matrix_ring_bottom
          shift: [p-.5px+WT,-.5py-WT]
        - ref: matrix_ring_bottom
          shift: [.5px+WT,-.5py-WT]
        - ref: matrix_middle_bottom
          shift: [p-.5px+WT,-.5py-WT]
        - ref: matrix_middle_bottom
          shift: [.5px-p-WT,-.5py-WT]
        - ref: matrix_index_bottom
          shift: [-.5px-WT,-.5py-WT]
        - ref: matrix_index_bottom
          shift: [1-WT,-.5py-WT]
        - ref: thumbfan_near_thumb
          shift: [-.5px-WT,-.5py-WT]
        - ref: thumbfan_near_thumb
          shift: [.5px,-.5py-WT]
        - ref: thumbfan_home_thumb
          shift: [-.5px,-.5py-WT]
        - ref: thumbfan_home_thumb
          shift: [.5px,-.5py-WT]
        - ref: thumbfan_far_thumb
          shift: [-.5px,-.5py-WT]
        - ref: thumbfan_far_thumb
          shift: [.5px+WT,-.5py-WT]
        - ref: thumbfan_far_thumb
          shift: [.5px+WT,.5py-WT]
        - ref: matrix_inner_bottom
          shift: [.5px+56+WT,-.5py-WT]
        - ref: matrix_inner_top
          shift: [.5px+56+WT,.5py+WT]
        - ref: matrix_index_top
          shift: [-.5px+p+WT,.5py+WT]
        - ref: matrix_middle_top
          shift: [.5px+WT,.5py+WT]
        - ref: matrix_middle_top
          shift: [-.5px-WT,.5py+WT]
        - ref: matrix_ring_top
          shift: [.5px-p-WT,.5py+WT]
        - ref: matrix_ring_top
          shift: [-.5px-WT,.5py+WT]
        - ref: matrix_pinky_top
          shift: [.5px-p-WT,.5py+WT]
  inner_base:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_outer_bottom
          shift: [-.5px, -.5py]
        - ref: matrix_pinky_bottom
          shift: [.5px,-.5py]
        - ref: matrix_ring_bottom
          shift: [p-.5px,-.5py]
        - ref: matrix_ring_bottom
          shift: [.5px,-.5py]
        - ref: matrix_middle_bottom
          shift: [p-.5px,-.5py]
        - ref: matrix_middle_bottom
          shift: [.5px-p,-.5py]
        - ref: matrix_index_bottom
          shift: [-.5px,-.5py]
        - ref: matrix_index_bottom
          shift: [1,-.5py]
        - ref: thumbfan_near_thumb
          shift: [-.5px,-.5py]
        - ref: thumbfan_near_thumb
          shift: [.5px,-.5py]
        - ref: thumbfan_home_thumb
          shift: [-.5px,-.5py]
        - ref: thumbfan_home_thumb
          shift: [.5px,-.5py]
        - ref: thumbfan_far_thumb
          shift: [-.5px,-.5py]
        - ref: thumbfan_far_thumb
          shift: [.5px,-.5py]
        - ref: thumbfan_far_thumb
          shift: [.5px,.5py]
        - ref: matrix_inner_bottom
          shift: [.5px+56,-.5py]
        - ref: matrix_inner_top
          shift: [.5px+56,.5py]
        - ref: matrix_index_top
          shift: [-.5px+p,.5py]
        - ref: matrix_middle_top
          shift: [.5px,.5py]
        - ref: matrix_middle_top
          shift: [-.5px,.5py]
        - ref: matrix_ring_top
          shift: [.5px-p,.5py]
        - ref: matrix_ring_top
          shift: [-.5px,.5py]
        - ref: matrix_pinky_top
          shift: [.5px-p,.5py]
pcbs:
  left:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: matrix_inner_top
          shift: [22,-10]
          rotate: -90
cases:
  base:
    - name: base
      extrude: 2
  _walls_subtract:
    - name: inner_base
      extrude: 10
  _walls_add:
    - name: base
      extrude: 10
  walls:
    - what: case
      name: _walls_add
      operation: add
    - what: case
      name: _walls_subtract
      operation: subtract
  main:
    - what: case
      name: base
      operation: add
    - what: case
      name: walls
      operation: add
