meta:
  engine: 4.1.0
units:
  $default_width: 18
  $default_height: 17
  kx: cx
  ky: cy
  p: 2
  px: kx + p * 2 
  py: ky + p * 2
  WT: 2
points:
  zones:
    matrix:
      key:
        padding: cy
        spread: cx
      anchor:
        rotate: 5
      columns:
        outer:
        pinky:
        ring:
          key.origin: [-12, -19]
          key.stagger: 12
        middle:
          key.stagger: 5
        index:
          key.stagger: -6
        inner:
          key.stagger: 0
      rows:
        bottom:
        home:
        top:
    thumbcluster:
      key: 
        padding: cy
        spread: cx
      anchor:
        ref: matrix_inner_bottom
        shift: [-5, -39]
        rotate: -20
      columns:
        left:
        right:
      rows:
        bottom:
        top:
  rotate: -20
  mirror:
    ref: matrix_pinky_home
    distance: 300
outlines:
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_middle_top
          shift: [2.5kx+p, .5py]
        - ref: matrix_middle_top
          shift: [-3.5kx-p, .5py]
        - ref: matrix_outer_bottom
          shift: [-.5px,-.5py]
        - ref: matrix_pinky_bottom
          shift: [3kx+p,-.5py]
        - ref: thumbcluster_left_bottom
          shift: [-.5px,-.5py]
        - ref: thumbcluster_right_bottom
          shift: [.5px,-.5py]
        - ref: thumbcluster_right_top
          shift: [.5px,.5py]
        - ref: matrix_inner_bottom
          shift: [.5px,-.5py]

     
  
pcbs:
  left:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      MCU:
        what: xiao-ble
        where:
          ref: matrix_inner_top
          shift: [22,-2]
          rotate: 0
cases:
  base:
    - name: board
      extrude: 2
