meta:
  engine: 4.1.0
units:
  $default_width: 18
  $default_height: 17
  kx: cx
  ky: cy
  p: 2
  px: kx + p * 2 
  py: ky + p * 2
points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
      columns:
        outer:
          key.column_net: P0
        pinky:
          key.column_net: P1
        ring:
          key.stagger: 12
          key.column_net: P2
        middle:
          key.stagger: 5
          key.column_net: P3
        index:
          key.stagger: -6
          key.column_net: P4
        inner:
          key.stagger: 0
          key.column_net: P5
      rows:
        bottom:
          row_net: P6
        home:
          row_net: P7
        top:
          row_net: P8
    thumbcluster:
      key: 
        padding: ky
        spread: kx
      anchor:
        ref: matrix_inner_bottom
        shift: [-5, -39]
        rotate: -20
      columns:
        left:
          key.column_net: P9
        right:
          key.column_net: P10
      rows:
        bottom:
          row_net: P6
        top:
          row_net: P7
outlines:
  switch_holes:
    - what: rectangle
      where: true
      size: [13.8, 13.8]
  base:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_middle_top
          shift: [2.5kx+p+2, .5py]
        - ref: matrix_middle_top
          shift: [-3.5kx-p, .5py]
        - ref: matrix_outer_bottom
          shift: [-.5px,-.5py]
        - ref: matrix_pinky_bottom
          shift: [3kx+p,-.5py]
        - ref: thumbcluster_left_bottom
          shift: [-.5px,.5py]
        - ref: thumbcluster_left_bottom
          shift: [-.5px,-.5py]
        - ref: thumbcluster_right_bottom
          shift: [.5px,-.5py]
        - ref: thumbcluster_right_top
          shift: [.5px,.5py]
        - ref: thumbcluster_left_top
          shift: [.5px,.5py]
        - ref: matrix_inner_bottom
          shift: [.5px+2,-.5py]
  mcu:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_inner_home
          shift: [.5px,5]
        - ref: matrix_inner_home
          shift: [.5kx+22,5]
        - ref: matrix_middle_top 
          shift: [2.5kx+22, .5py]
        - ref: matrix_middle_top
          shift: [2.5kx+p, .5py]
  board:
    - what: outline
      operation: add
      name: base
    - what: outline
      operation: add
      name: mcu

     
  
pcbs:
  left:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: cleoloide/switch_choc_v1_v2
        where: true
        params:
          reversible: true
          hotswap: true
          hotswap_pads_same_side: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: cleoloide/diode_tht_sod123
        where: true
        params:
          include_thru_hole_smd_pads: true
          include_traces_vias: true
          reversible: true
          include_tht: false
        
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      MCU:
        what: xiao-ble
        where:
          ref: matrix_middle_top
          shift: [2.5kx+11,0]
          rotate: 0
cases:
  base:
    - name: base
      extrude: 2
  sw_holes:
    - name: switch_holes
      extrude: 2
  switchplate:
    - what: case
      name: base
      operation: add
    - what: case
      name: sw_holes
      operation: subtract

